### PR TITLE
Added book modal

### PR DESCRIPTION
**Pull request by longy2k**
Screenshot 2023-09-25 at 5 41 05 PM
Screenshot 2023-09-25 at 5 41 24 PM

### CODE REVIEW

**Comment by MichaelShingo** [comment]
Given Morgan's redesign of the Add Book modal, should we wait on approving this?

**Comment by madaley1** [comment]
After reviewing, I do think I want to update this before merging.  Everything looks good here, but reason the redesign was proposed in the first place was because of a greater clarification concerning the API and how we need to interface with it. Given the new requirements and API endpoints, I'd like to connect on some necessary updates to make this work as intended. Feel free to @ me when you have time @longy2k and we can go over it!

**Comment by madaley1** [comment]
Ok, this is finally ready for merge. This is a massive PR. I don't think it ballooned per se, but it definitely is larger than originally expected. I have a few notes for improvement, as well as a bug that will need to be fixed that I'll be putting as an issue. Hopefully it's not too much to parse, as it definitely is dense. Let me know what y'all think!

**Review by MichaelShingo — APPROVED** [review]
Looks good! Couple questions: in books/POST is it setting the location field to a default value?

And are we doing ./ imports from now on?

**Review by madaley1 — APPROVED** [review]

**Comment by madaley1** [comment]
> Looks good! Couple questions: in books/POST is it setting the location field to a default value?
> 
> And are we doing ./ imports from now on?

Yes, it is setting a default value as it will likely be in a sorting/staging area before its put into the library

And ./ imports I'm still a bit back and forth on. For index files they seem to be acceptable, and if it's only a ./ I could see an argument made, but any backtracking, either with `../` or `../../` etc should use an `@/` instead.

**Pull request merged**
